
# -*- makefile -*-
# Do not edit this file.
# This file will be overwritten by the project setup script.

RAW_SIMICS_BASE=/home/gabriel/Documents/Simics/simics-6.0.185
RAW_SIMICS_MODEL_BUILDER=/home/gabriel/Documents/Simics/simics-6.0.185
RAW_EML_PACKAGE=
RAW_DODOC_PKG=/home/gabriel/Documents/Simics/simics-6.0.185

RAW_SIMICS_PACKAGE_LIST=/home/gabriel/simics-projects/proyecto2-empotrados/.package-list

INCLUDE_PATHS = /home/gabriel/Documents/Simics/simics-6.0.185/src/include
CXX_INCLUDE_PATHS = /home/gabriel/Documents/Simics/simics-6.0.185/linux64/api
DML_INCLUDE_PATHS = /home/gabriel/Documents/Simics/simics-6.0.185/linux64/bin/dml/api
HOST_TYPE = linux64
